// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKmaHpaFKMWZkzK4_9migyA6EfP0iU5Og',
    appId: '1:589066486292:web:b5b2cf2f63a12f40985d01',
    messagingSenderId: '589066486292',
    projectId: 'my-shop-3deca',
    authDomain: 'my-shop-3deca.firebaseapp.com',
    storageBucket: 'my-shop-3deca.appspot.com',
    measurementId: 'G-CGNM3M5RFH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdvqpOwuj_kBonO93RuJL-0rfhgjxNeXE',
    appId: '1:589066486292:android:2338127a1edf9426985d01',
    messagingSenderId: '589066486292',
    projectId: 'my-shop-3deca',
    storageBucket: 'my-shop-3deca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn6xEGSv2RGVmCjGC_FEV-t3VpKSOCxeE',
    appId: '1:589066486292:ios:ea8f6f0112a60285985d01',
    messagingSenderId: '589066486292',
    projectId: 'my-shop-3deca',
    storageBucket: 'my-shop-3deca.appspot.com',
    iosBundleId: 'com.example.myShop',
  );
}
